// components/PrintDeck.tsx
import { useMemo } from "react";
import { Button } from "./ui/button";
import { Card } from "./ui/card";
import { ScoringResult } from "../utils/scoringEngine";
import { buildSlides } from "./buildSlides"; // <- we’ll create this next

interface PrintDeckProps {
  results: ScoringResult;
  onBack: () => void;
  onOpenBenchmark?: () => void;
  brandName?: string;
  logoUrl?: string;
}

export function PrintDeck({
  results,
  onBack,
  onOpenBenchmark,
  brandName = "SectorSync",
  logoUrl,
}: PrintDeckProps) {
  const slides = useMemo(() => buildSlides(results, { onOpenBenchmark }), [results, onOpenBenchmark]);

  return (
    <div className="min-h-screen bg-white text-black">
      {/* Toolbar (hidden in print view) */}
      <div className="sticky top-0 z-10 flex items-center justify-between gap-3 p-3 border-b bg-white print:hidden">
        <div className="flex items-center gap-2">
          {logoUrl && <img src={logoUrl} alt="Logo" className="h-6 w-auto" />}
          <span className="font-medium">{brandName} — Print Deck</span>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={() => window.print()}>
            Print / Save PDF
          </Button>
          <Button variant="outline" onClick={onBack}>
            Back
          </Button>
        </div>
      </div>

      {/* Slides */}
      <div className="mx-auto w-full max-w-5xl p-6">
        {slides.map((slide, i) => (
          <div
            key={i}
            className="print-page bg-white text-black border rounded-xl p-6 mb-8"
          >
            {/* Optional header/footer */}
            <div className="mb-4 flex items-center justify-between">
              <div className="text-sm opacity-70">{brandName}</div>
              <div className="text-sm opacity-70">Slide {i + 1} / {slides.length}</div>
            </div>

            <div className="page-content">{slide}</div>

            <div className="mt-6 flex items-center justify-between">
              <div className="text-xs opacity-70">Generated by {brandName}</div>
              <div className="text-xs opacity-70">{new Date().toLocaleDateString()}</div>
            </div>
          </div>
        ))}
      </div>

      {/* Print layout rules */}
      <style>{`
        @media print {
          @page { size: auto; margin: 12.7mm; } /* ~0.5 inch margins */
          .print\\:hidden { display: none !important; }
          body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
          .print-page {
            page-break-after: always;
            break-after: page;
            box-shadow: none !important;
            border: none !important;
            margin: 0 !important;
            padding: 0 !important;
          }
          .page-content {
            padding: 10mm 6mm;
          }
        }
      `}</style>
    </div>
  );
}
